language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
before_script: []

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed morehwachege/udagram-api-feed:v3

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user morehwachege/udagram-api-user:v3

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend morehwachege/udagram-frontend:v3

  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy morehwachege/reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push morehwachege/udagram-api-feed:v3
  - docker push morehwachege/udagram-api-user:v3
  - docker push morehwachege/udagram-frontend:v3
  - docker push morehwachege/reverseproxy:v3
