apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/morehwachege/udagram-frontend:v8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          envFrom:
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: env-configmap
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    run: frontend
